### ISSUE TITLE
inline assembly from fp* benchmarks to _libs/util.h

### ISSUE THREAD

**Issue by EkremA** [pouriahassani/AxE#10]
Concerning the `dev_fp*` branches especially, the benchmark C-files in `sw/programs/fp*/main.c`.
Transfer all inline assembly functions, that means all "hardcoded instructions" into `sw/_libs/util.h`

**Comment by pouriahassani** [comment]
All the inline fp* functions are included to the util.c and util.h files. For running the stand alone fp*.c like you need to remove the definition of online assembly function. Otherwise it will cause multiple definition of them while compiling the codes if you include ./../../_libs/util.h file in the fp*.c codes
